version: "3.9"

services:
    bot:
        image: gridbot
        build:
          context: .
        container_name: gridbot
        tty: true
        volumes:
          - ./configs:/app/configs
          - ./logs:/app/logs
          - /etc/timezone:/etc/timezone:ro
        command: python main.py configs/config.yml

