api:
  key: YOUR_API_KEY
  secret: YOUR_API_SECRET

grid_bot:
  pair: eth_jpy  # In the form of base_quote
  grid_num: 100
  base_usage: 0.8  #  The ratio of base currency (eth) to use
  quote_usage: 0.8  # The ratio of quote currency (jpy) to use
  price_interval: 1000
  check_interval: 1 # Time between checking the update
  order_limit : 10
  reset_interval: 12  # reset the bot in 12 hours

user:
  name: YOUR_NAME

discord:
  info: YOUR_INFO_WEBHOOK
  error: YOUR_ERR_WEBHOOK

logging:
  level: INFO


db:
  firestore: /pat/to/serviceAccountKey.json
